# Generated by Django 5.0.4 on 2024-04-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("GRE_score", models.IntegerField()),
                ("TOEFL_score", models.IntegerField()),
                ("university_name", models.CharField(max_length=200)),
                ("GPA", models.FloatField()),
            ],
        ),
    ]
