# Generated by Django 5.0.4 on 2024-04-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gradvisor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicant",
            old_name="GRE_score",
            new_name="greQuantitativeScore",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="TOEFL_score",
            new_name="greVerbalScore",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="university_name",
            new_name="underGraduateUniversity",
        ),
        migrations.AddField(
            model_name="applicant",
            name="greAWAScore",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicant",
            name="toeflScore",
            field=models.IntegerField(default=80.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicant",
            name="workExperience",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
