# Generated by Django 5.0.4 on 2024-04-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gradvisor", "0002_rename_gre_score_applicant_grequantitativescore_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="passwordVal",
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name="applicant",
            name="username",
            field=models.CharField(default=False, max_length=100),
        ),
    ]
