# Generated by Django 5.0.4 on 2024-04-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gradvisor", "0004_applicant_researchexperience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicant",
            old_name="GPA",
            new_name="cgpa",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="researchExperience",
            new_name="confPubs",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="greAWAScore",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="greQuantitativeScore",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="greVerbalScore",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="toeflScore",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="underGraduateUniversity",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="workExperience",
        ),
        migrations.AddField(
            model_name="applicant",
            name="gre_score",
            field=models.IntegerField(default=270),
        ),
        migrations.AddField(
            model_name="applicant",
            name="industryExp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="applicant",
            name="internExp",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="applicant",
            name="journalPubs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="applicant",
            name="researchExp",
            field=models.IntegerField(default=0),
        ),
    ]
